resources:
- tasks/git-clone.yaml
- tasks/maven11.yaml
- tasks/maven17.yaml
- tasks/maven21.yaml
- tasks/push-app.yaml
- tasks/publish-test-report.yaml
- tasks/print-csv-table.yaml
- tasks/semgrep-scan.yaml
- tasks/owasp-dependency-check.yaml