resources:
- pvc/maven-cache-pvc.yaml
- tasks/git-clone.yaml
- tasks/maven11.yaml
- tasks/maven17.yaml
- tasks/maven21.yaml
- tasks/push-app.yaml
- tasks/publish-test-report.yaml
- tasks/print-csv-table.yaml
- tasks/semgrep-scan.yaml
- tasks/maven21-playwright.yaml
- tasks/playwright-e2e.yaml
- tasks/gitleaks-scan.yaml
- tasks/trivy-scan.yaml
- tasks/wapiti-scan.yaml
- tasks/owasp-dependency-check.yaml
- tasks/owasp-dependency-check-update.yaml
- tasks/pipeline-summary.yaml