apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dependency-check-db
  namespace: quarkusdroneshop-cicd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 20Gi
